"use client";

import { useSearchParams } from "next/navigation";
import { useEffect, useState, Suspense, useRef } from "react";
import { DICT, Language } from "@/lib/i18n";

type TraitPair = [string, string]; // e.g. ['B','F']
const AXES: TraitPair[] = [['B', 'F'], ['L', 'H'], ['G', 'V'], ['S', 'P']];

// Map new codes → old image filenames (images are still named by the old R/A/L/E/C/D/S/U system)
const CODE_TO_IMAGE: Record<string, string> = {
  BLGS: 'rlcs', FHVP: 'aedu', BHGS: 'recs', FLVP: 'aldu',
  FLGS: 'alcs', BLGP: 'rlcu', BLVS: 'rlds', BLVP: 'rldu',
  BHGP: 'recu', BHVS: 'reds', BHVP: 'redu', FLGP: 'alcu',
  FLVS: 'alds', FHGS: 'aecs', FHGP: 'aecu', FHVS: 'aeds',
};

const CODE_TO_SLUG: Record<string, string> = {
  BLGS: 'the-executive', FHVP: 'the-campaigner', BHGS: 'the-defender', FLVP: 'the-visionary',
  FLGS: 'the-analyst', BLGP: 'the-director', BLVS: 'the-architect', BLVP: 'the-commander',
  BHGP: 'the-provider', BHVS: 'the-oracle', BHVP: 'the-mentor', FLGP: 'the-optimizer',
  FLVS: 'the-core-breaker', FHGS: 'the-artisan', FHGP: 'the-entertainer', FHVS: 'the-dreamer',
};

function SubmitContent() {
  const searchParams = useSearchParams();
  const session = searchParams.get("session") || "UNKNOWN";
  const rawAns = searchParams.get("ans") || "";
  const langQuery = searchParams.get("lang") as Language;

  const [lang, setLang] = useState<Language>('zh');
  const [desiredPcts, setDesiredPcts] = useState<number[]>([]);
  const [showGuide, setShowGuide] = useState(false);
  const [guideCopied, setGuideCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [showShareModal, setShowShareModal] = useState(false);
  const [shareToast, setShareToast] = useState('');

  // Paywall State
  const [unlocked, setUnlocked] = useState(false);
  const [keyCode, setKeyCode] = useState('');
  const [keyError, setKeyError] = useState(false);

  const reportRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (langQuery === 'zh' || langQuery === 'en') setLang(langQuery);
  }, [langQuery]);

  const dict = DICT[lang];

  // Parse 60 answers
  const parsed = rawAns.toUpperCase().padEnd(60, 'A').replace(/[^AB]/g, 'A');
  const countB = (s: string) => s.split('').filter(c => c === 'B').length;
  const groups = [parsed.substring(0, 15), parsed.substring(15, 30), parsed.substring(30, 45), parsed.substring(45, 60)];

  // Convert to 0-100 scale where 0 is 100% Left Trait, 100 is 100% Right Trait
  // 15 questions per group, countB ranges 0-15
  const basePcts = groups.map(g => Math.round((countB(g) / 15) * 100));

  const traits = [
    basePcts[0] < 50 ? 'B' : 'F',
    basePcts[1] < 50 ? 'L' : 'H',
    basePcts[2] < 50 ? 'G' : 'V',
    basePcts[3] < 50 ? 'S' : 'P',
  ];

  const code = traits.join('');
  const profile = (dict.archetypes as any)[code] || dict.archetypes['DEFAULT'];
  const hasImage = true; // All 16 combinations now have images generated

  // Init desired pct to base pct
  useEffect(() => {
    if (desiredPcts.length === 0 && basePcts.length > 0) {
      setDesiredPcts([...basePcts]);
    }
  }, [basePcts.join('')]);

  // Generate tuning guide
  const generateGuide = () => {
    const lines: string[] = [];
    if (desiredPcts.length === 4) {
      for (let i = 0; i < 4; i++) {
        // use dict.generateTuningPrompt
        const promptBlock = (dict as any).generateTuningPrompt(i, basePcts[i], desiredPcts[i]);
        if (promptBlock) {
          lines.push(promptBlock);
        }
      }
    }
    return lines;
  };

  const guideLines = generateGuide();
  const noChange = guideLines.length === 0;

  const guideText = noChange ? '' :
    `# ==========================================\n# SYSTEM OVERRIDE DIRECTIVES\n# GENERATED BY: OpenClaw Tuning Protocol\n# ==========================================\n\n${guideLines.join('\n')}\n# [END OF DIRECTIVES]`;

  // TraitBar for MBTI Report
  // pctB is 0-100. 0 means 100% A(Left), 100 means 100% B(Right)
  const TraitBar = ({ leftLabel, rightLabel, pctB, color }: { leftLabel: string; rightLabel: string; pctB: number; color: string }) => {
    const dominantB = pctB >= 50;
    const valLeft = 100 - pctB;
    const valRight = pctB;
    return (
      <div style={{ marginBottom: 20 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6 }}>
          <span className="trait-label" style={{ fontWeight: !dominantB ? 700 : 400, color: !dominantB ? color : '#a0aec0' }}>{leftLabel}</span>
          <span className="trait-label" style={{ fontWeight: dominantB ? 700 : 400, color: dominantB ? color : '#a0aec0' }}>{rightLabel}</span>
        </div>
        <div className="mbti-bar-container">
          <div className="mbti-bar-left" style={{ width: `${valLeft}%`, backgroundColor: !dominantB ? color : '#e2e8f0' }}></div>
          <div className="mbti-bar-right" style={{ width: `${valRight}%`, backgroundColor: dominantB ? color : '#e2e8f0' }}></div>
        </div>
        <div style={{ textAlign: 'center', fontSize: 11, color: '#a0aec0', marginTop: 4, fontFamily: 'monospace' }}>
          {!dominantB ? valLeft : valRight}%
        </div>
      </div>
    );
  };

  const labels = [
    [dict.ruleAbiding, dict.autonomous],
    [dict.logical, dict.empathetic],
    [dict.cautious, dict.creative],
    [dict.system, dict.user],
  ];

  const getShareText = () => {
    const baseUrl = typeof window !== 'undefined' ? window.location.origin : '';
    const shareUrl = CODE_TO_SLUG[code]
      ? `${baseUrl}/you-are/${CODE_TO_SLUG[code]}`
      : baseUrl;
    return lang === 'zh'
      ? `这个 AI 的性格是 ${profile.title} (${code}) 🔮 — 来给你常用的 AI 测一测？\n${shareUrl}`
      : `This AI's personality is ${profile.title} 🔮 (${code}) — Test your AI:\n${shareUrl}`;
  };

  const captureCanvas = async (): Promise<HTMLCanvasElement | null> => {
    if (!reportRef.current) return null;
    const animElements = reportRef.current.querySelectorAll('.animate-slide-up');
    animElements.forEach(el => el.classList.remove('animate-slide-up'));
    try {
      const html2canvas = (await import('html2canvas')).default;
      const canvas = await html2canvas(reportRef.current!, {
        scale: Math.max(window.devicePixelRatio * 2, 4),
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff',
        logging: false,
      });
      return canvas;
    } finally {
      animElements.forEach(el => el.classList.add('animate-slide-up'));
    }
  };

  const handleExport = async () => {
    if (isExporting) return;
    setIsExporting(true);
    try {
      const canvas = await captureCanvas();
      if (!canvas) return;
      const dataUrl = canvas.toDataURL('image/png');
      const link = document.createElement('a');
      link.download = `AI_Profile_${code}_${session.substring(0, 6)}.png`;
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error('Export failed', err);
    } finally {
      setIsExporting(false);
    }
  };

  const downloadCanvas = (canvas: HTMLCanvasElement) => {
    const dataUrl = canvas.toDataURL('image/png');
    const link = document.createElement('a');
    link.download = `AI_Profile_${code}_${session.substring(0, 6)}.png`;
    link.href = dataUrl;
    link.click();
  };

  const shareToPlatform = async (platform: string) => {
    if (isExporting) return;
    setIsExporting(true);
    try {
      const canvas = await captureCanvas();
      if (!canvas) return;

      const shareText = getShareText();
      const blob = await new Promise<Blob>(resolve => canvas.toBlob(b => resolve(b!), 'image/png'));
      const file = new File([blob], 'AI_Profile.png', { type: 'image/png' });

      // Mobile: try native Web Share API first
      if (navigator.share && navigator.canShare) {
        const shareData: ShareData = { text: shareText, files: [file] };
        if (navigator.canShare(shareData)) {
          await navigator.share(shareData);
          setShowShareModal(false);
          return;
        }
      }

      // Desktop fallback
      if (platform === 'x') {
        downloadCanvas(canvas);
        await navigator.clipboard.writeText(shareText);
        const tweetText = encodeURIComponent(shareText.replace(/\n/g, ' '));
        window.open(`https://twitter.com/intent/tweet?text=${tweetText}`, '_blank');
        setShowShareModal(false);
        setShareToast(lang === 'zh' ? '图片已下载，文案已复制，X 已打开' : 'Image downloaded, text copied, X opened');
      } else {
        downloadCanvas(canvas);
        await navigator.clipboard.writeText(shareText);
        setShowShareModal(false);
        const platformNames: Record<string, string> = {
          xhs: '小红书',
          wechat: '微信',
          moments: '朋友圈',
        };
        const name = lang === 'zh' ? (platformNames[platform] || platform) : platform;
        setShareToast(lang === 'zh' ? `图片已保存，文案已复制，请打开${name}发布` : `Image saved, text copied. Open ${name} to post`);
      }
    } catch (err) {
      console.error('Share failed', err);
    } finally {
      setIsExporting(false);
    }
  };

  useEffect(() => {
    if (!shareToast) return;
    const t = setTimeout(() => setShareToast(''), 3000);
    return () => clearTimeout(t);
  }, [shareToast]);

  return (
    <div style={{ minHeight: '100dvh', background: '#f5f7fa' }}>
      {/* Nav */}
      <nav style={{
        padding: '12px 16px', background: 'rgba(255,255,255,0.92)', backdropFilter: 'blur(12px)',
        borderBottom: '1px solid #e2e8f0', position: 'sticky', top: 0, zIndex: 50,
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      }}>
        <a href={`/?lang=${lang}`} style={{ fontSize: 15, fontWeight: 700, color: '#2d3748', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ width: 28, height: 28, borderRadius: '50%', background: '#f7fafc', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: 12 }}>❖</span>
          Profiler
        </a>
        <span style={{ fontSize: 11, color: '#a0aec0', fontFamily: 'monospace', background: '#f7fafc', padding: '4px 10px', borderRadius: 6 }}>{session.substring(0, 6)}</span>
      </nav>

      <main style={{ maxWidth: 560, margin: '0 auto', padding: '24px 16px 60px' }}>

        {/* Report Wrapper for Exporting */}
        <div ref={reportRef} style={{ background: '#ffffff', paddingBottom: '1px' }}>

          {/* Hero */}
          <div className="animate-slide-up" style={{ textAlign: 'center', marginBottom: 24, paddingTop: 16 }}>
            <div style={{ display: 'inline-block', padding: '4px 16px', borderRadius: 999, fontSize: 11, fontWeight: 700, letterSpacing: 3, color: '#fff', marginBottom: 12, background: profile.color || '#718096' }}>
              {code}
            </div>
            <h1 style={{ fontSize: '1.75rem', color: profile.color || '#2d3748', marginBottom: 10, lineHeight: 1.2 }}>{profile.title}</h1>
            <p style={{ fontSize: '0.9375rem', color: '#718096', fontStyle: 'italic', lineHeight: 1.5, maxWidth: 380, margin: '0 auto' }}>{profile.tagline}</p>
          </div>

          {/* Avatar */}
          <div className="animate-slide-up" style={{ position: 'relative', width: '100%', maxWidth: 300, margin: '0 auto 28px', aspectRatio: '1', borderRadius: 24, overflow: 'hidden' }}>
            <div style={{ position: 'absolute', inset: 0, borderRadius: 24, background: '#f0f4f8' }} />
            {hasImage ? (
              <img src={`/images/avatar_${CODE_TO_IMAGE[code] || code.toLowerCase()}.png`} alt={code} style={{ width: '100%', height: '100%', objectFit: 'contain', position: 'relative', zIndex: 1 }} />
            ) : (
              <div style={{ width: '100%', height: '100%', background: '#f7fafc', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
                <div style={{ fontSize: 48, marginBottom: 8 }}>🎭</div>
                <p style={{ fontSize: 12, color: '#a0aec0', textAlign: 'center', padding: '0 20px' }}>{lang === 'zh' ? `${code} 人格画像生成中…` : `Generating ${code} portrait…`}</p>
              </div>
            )}
          </div>

          {/* Trait Bars */}
          <div className="mbti-card animate-slide-up" style={{ marginBottom: 16 }}>
            <h3 style={{ fontSize: '1rem', marginBottom: 16, color: '#2d3748' }}>{dict.cogResonance}</h3>
            {basePcts.map((p, i) => (
              <TraitBar key={i} leftLabel={labels[i][0]} rightLabel={labels[i][1]} pctB={p} color={profile.color || '#4298b4'} />
            ))}
          </div>

          {/* Deep Report */}
          <div className="mbti-card animate-slide-up" style={{ marginBottom: 16 }}>
            <h3 style={{ fontSize: '1.125rem', marginBottom: 14, color: '#2d3748', borderBottom: '1px solid #e2e8f0', paddingBottom: 12 }}>
              {lang === 'zh' ? '📖 全息解读' : '📖 Deep Analysis'}
            </h3>
            <p style={{ fontSize: '0.9375rem', color: '#4a5568', lineHeight: 1.8, marginBottom: 16 }}>{profile.intro}</p>

            {profile.deepAnalysis && (
              <div style={{ marginBottom: 20 }}>
                {profile.deepAnalysis.split('\n\n').map((para: string, i: number) => (
                  <p key={i} style={{ fontSize: '0.875rem', color: '#4a5568', lineHeight: 1.8, marginBottom: 14, textIndent: '2em' }}>{para}</p>
                ))}
              </div>
            )}

            <div style={{ display: 'grid', gap: 12, marginBottom: 20 }}>
              <div style={{ background: '#f0fff4', border: '1px solid #c6f6d5', borderRadius: 14, padding: '14px 16px' }}>
                <h4 style={{ fontSize: '0.875rem', fontWeight: 700, color: '#276749', marginBottom: 6 }}>✅ {lang === 'zh' ? '高潜优势' : 'Strengths'}</h4>
                <p style={{ fontSize: '0.8125rem', color: '#2f855a', lineHeight: 1.7 }}>{profile.strengths}</p>
              </div>
              <div style={{ background: '#fff5f5', border: '1px solid #fed7d7', borderRadius: 14, padding: '14px 16px' }}>
                <h4 style={{ fontSize: '0.875rem', fontWeight: 700, color: '#9b2c2c', marginBottom: 6 }}>⚠️ {lang === 'zh' ? '注意盲区' : 'Weaknesses'}</h4>
                <p style={{ fontSize: '0.8125rem', color: '#c53030', lineHeight: 1.7 }}>{profile.weaknesses}</p>
              </div>
            </div>

            <div style={{ borderLeft: `3px solid ${profile.color || '#4298b4'}`, paddingLeft: 14 }}>
              <h4 style={{ fontSize: '0.875rem', fontWeight: 700, color: '#2d3748', marginBottom: 6 }}>🚀 {lang === 'zh' ? '最佳进化路线' : 'Best Path Forward'}</h4>
              <p style={{ fontSize: '0.8125rem', color: '#4a5568', lineHeight: 1.7 }}>{profile.career}</p>
            </div>
          </div>

          {/* ===== TUNING WORKSHOP (DIFFERENTIAL ENGINE) ===== */}
          {desiredPcts.length === 4 && (
            <div className="mbti-card animate-slide-up" style={{ marginBottom: 16, border: '1px solid #e9d8fd' }}>
              <h3 style={{ fontSize: '1.125rem', marginBottom: 8, color: '#88619a' }}>{dict.tuningTitle}</h3>
              <p style={{ fontSize: '0.8125rem', color: '#718096', lineHeight: 1.7, marginBottom: 20 }}>{dict.tuningDesc}</p>

              {/* Trait Sliders */}
              <div style={{ display: 'grid', gap: 20, marginBottom: 24 }}>
                {AXES.map((pair, i) => {
                  const names = dict.traitNames as Record<string, string>;
                  const current = basePcts[i];
                  const desired = desiredPcts[i];
                  const delta = Math.abs(desired - current);
                  const hasChanged = delta >= 5;

                  return (
                    <div key={i} style={{
                      padding: '16px 14px', borderRadius: 12,
                      background: hasChanged ? 'rgba(136, 97, 154, 0.05)' : '#f7fafc',
                      border: `1px solid ${hasChanged ? 'rgba(136, 97, 154, 0.3)' : '#e2e8f0'}`,
                      transition: 'all 0.2s',
                    }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 12 }}>
                        <span style={{ fontSize: 13, fontWeight: desired < 50 ? 700 : 500, color: desired < 50 ? '#88619a' : '#718096' }}>{names[pair[0]]}</span>
                        {hasChanged && <span style={{ fontSize: 11, color: '#88619a', fontWeight: 600, background: '#fff', padding: '2px 6px', borderRadius: 6, border: '1px solid #e9d8fd' }}>Δ {delta}%</span>}
                        <span style={{ fontSize: 13, fontWeight: desired >= 50 ? 700 : 500, color: desired >= 50 ? '#88619a' : '#718096' }}>{names[pair[1]]}</span>
                      </div>

                      <div style={{ position: 'relative', height: 24, display: 'flex', alignItems: 'center' }}>
                        {/* Current marker */}
                        <div style={{
                          position: 'absolute', top: 4, bottom: 4, width: 3, background: '#cbd5e0',
                          left: `calc(${current}% - 1.5px)`, borderRadius: 2, pointerEvents: 'none', zIndex: 0
                        }} title={dict.tuningCurrent} />

                        <input
                          type="range"
                          min="0" max="100"
                          value={desired}
                          onChange={(e) => {
                            const newPcts = [...desiredPcts];
                            newPcts[i] = parseInt(e.target.value);
                            setDesiredPcts(newPcts);
                            setShowGuide(false);
                          }}
                          className="mbti-slider"
                        />
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Generate button */}
              <button className="mbti-btn" onClick={() => setShowGuide(true)} style={{
                width: '100%', background: noChange ? '#e2e8f0' : '#88619a',
                color: noChange ? '#a0aec0' : '#fff', border: 'none',
                cursor: noChange ? 'default' : 'pointer',
              }}>
                {dict.tuningGenerate}
              </button>

              {/* Guide result */}
              {showGuide && (
                <div style={{ marginTop: 16 }}>
                  {noChange ? (
                    <div className="note-box" style={{ background: '#f0fff4', borderColor: '#c6f6d5', color: '#276749' }}>
                      {dict.tuningNoChange}
                    </div>
                  ) : (
                    <div style={{ background: '#1a202c', borderRadius: 14, padding: '16px 16px 20px', overflow: 'hidden' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 12 }}>
                        <div style={{ width: 10, height: 10, borderRadius: '50%', background: '#ff5f56' }} />
                        <div style={{ width: 10, height: 10, borderRadius: '50%', background: '#ffbd2e' }} />
                        <div style={{ width: 10, height: 10, borderRadius: '50%', background: '#27c93f' }} />
                        <span style={{ marginLeft: 8, fontSize: 12, color: '#a0aec0', fontFamily: 'monospace' }}>system-override.sh</span>
                      </div>

                      <p style={{ fontSize: '0.8125rem', color: '#e2e8f0', marginBottom: 16 }}>{dict.tuningResultDesc}</p>

                      <div style={{ position: 'relative' }}>
                        <div style={{
                          background: '#0d1117', border: '1px solid #2d3748', borderRadius: 8, padding: 16,
                          fontSize: '0.75rem', color: '#3fb950', lineHeight: 1.6, marginBottom: 16,
                          whiteSpace: 'pre-wrap', fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
                          maxHeight: '400px', overflowY: 'auto',
                          filter: unlocked ? 'none' : 'blur(5px)',
                          userSelect: unlocked ? 'text' : 'none',
                          transition: 'filter 0.3s ease'
                        }}>
                          {guideText}
                        </div>

                        {/* Paywall Overlay */}
                        {!unlocked && (
                          <div style={{
                            position: 'absolute', top: 0, left: 0, right: 0, bottom: 16,
                            display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
                            background: 'rgba(13, 17, 23, 0.75)', borderRadius: 8, zIndex: 10,
                            padding: 20, textAlign: 'center'
                          }}>
                            <div style={{ fontSize: 24, marginBottom: 12 }}>🔒</div>
                            <h4 style={{ color: '#fff', fontSize: '1rem', marginBottom: 8 }}>{lang === 'zh' ? '解锁高级调教指令' : 'Unlock Premium Prompts'}</h4>
                            <p style={{ color: '#a0aec0', fontSize: '0.8125rem', marginBottom: 20 }}>
                              {lang === 'zh' ? '获取专业级 System Override 指令，极致压榨 AI 潜能。' : 'Get professional System Override directives to maximize AI potential.'}
                            </p>

                            <a href={lang === 'zh' ? (process.env.NEXT_PUBLIC_STORE_LINK_ZH || "https://afdian.net/a/YOUR_AFDIAN_ID") : (process.env.NEXT_PUBLIC_STORE_LINK || "https://388811932798.gumroad.com/l/ai-personality?code=PH50")} target="_blank" rel="noopener noreferrer" style={{
                              display: 'inline-block', background: '#eab308', color: '#1a202c',
                              padding: '10px 24px', borderRadius: 8, fontSize: '0.875rem', fontWeight: 700,
                              textDecoration: 'none', marginBottom: 20, boxShadow: '0 4px 14px rgba(234, 179, 8, 0.4)'
                            }}>
                              {lang === 'zh' ? (
                                <>🔑 购买解锁口令 <s style={{ opacity: 0.6, fontWeight: 400, margin: '0 4px' }}>¥19.9</s> ¥9.9</>
                              ) : (
                                <>🔑 Purchase License Key <s style={{ opacity: 0.6, fontWeight: 400, margin: '0 4px' }}>$9.99</s> $4.99</>
                              )}
                            </a>

                            <div style={{ display: 'flex', gap: 8, width: '100%', maxWidth: 280 }}>
                              <input
                                type="text"
                                placeholder={lang === 'zh' ? '输入你的解锁口令' : 'Enter License Key'}
                                value={keyCode}
                                onChange={(e) => { setKeyCode(e.target.value); setKeyError(false); }}
                                style={{
                                  flex: 1, padding: '8px 12px', borderRadius: 6, border: `1px solid ${keyError ? '#ef4444' : '#4a5568'}`,
                                  background: '#1a202c', color: '#fff', fontSize: '0.875rem', outline: 'none'
                                }}
                              />
                              <button
                                onClick={() => {
                                  const validKeyEN = process.env.NEXT_PUBLIC_UNLOCK_KEY || "GUMROAD_PRO";
                                  const validKeyZH = process.env.NEXT_PUBLIC_UNLOCK_KEY_ZH || "MBD_PRO";
                                  if (keyCode.trim() === validKeyEN || keyCode.trim() === validKeyZH || keyCode.trim() === "AFDIAN_PRO") {
                                    setUnlocked(true);
                                  } else {
                                    setKeyError(true);
                                  }
                                }}
                                style={{
                                  background: '#3b82f6', color: '#fff', border: 'none', borderRadius: 6,
                                  padding: '0 16px', fontSize: '0.875rem', fontWeight: 600, cursor: 'pointer'
                                }}
                              >
                                {lang === 'zh' ? '验证' : 'Verify'}
                              </button>
                            </div>
                            {keyError && <span style={{ color: '#ef4444', fontSize: '0.75rem', marginTop: 8 }}>{lang === 'zh' ? '口令错误，请重试' : 'Invalid key. Please try again.'}</span>}
                          </div>
                        )}
                      </div>

                      <button className="mbti-btn" onClick={() => {
                        navigator.clipboard.writeText(guideText);
                        setGuideCopied(true);
                        setTimeout(() => setGuideCopied(false), 2500);
                      }} style={{
                        width: '100%',
                        background: !unlocked ? '#4a5568' : (guideCopied ? '#38a169' : '#e2e8f0'),
                        color: !unlocked ? '#a0aec0' : (guideCopied ? '#fff' : '#1a202c'),
                        border: 'none', fontSize: '0.875rem',
                        cursor: !unlocked ? 'not-allowed' : 'pointer'
                      }} disabled={!unlocked}>
                        {guideCopied ? '✅ Copied to Clipboard' : dict.tuningCopy}
                      </button>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </div> {/* End Report Wrapper */}


        {/* Share Section */}
        <div style={{
          background: '#fff', border: '1px solid #e2e8f0', borderRadius: 16,
          padding: '16px 20px', marginBottom: 12,
          display: 'flex', flexDirection: 'column', gap: 10,
        }}>
          <p style={{ fontSize: 13, fontWeight: 700, color: '#2d3748', margin: 0, textAlign: 'center' }}>
            📤 {lang === 'zh' ? '分享结果' : 'Share Result'}
          </p>

          <button
            className="mbti-btn"
            style={{ width: '100%', fontSize: '0.9375rem', background: profile.color || '#667eea', color: '#fff', border: 'none' }}
            onClick={() => setShowShareModal(true)}
            disabled={isExporting}
          >
            🔮 {lang === 'zh' ? '分享到社交平台' : 'Share to Social'}
          </button>

          <button
            className="mbti-btn"
            style={{ width: '100%', fontSize: '0.875rem', background: '#edf2f7', color: '#2d3748', border: 'none' }}
            onClick={handleExport}
            disabled={isExporting}
          >
            {isExporting ? '...' : `📥 ${lang === 'zh' ? '下载分享卡片' : 'Download Share Card'}`}
          </button>
        </div>

        {/* Share Modal */}
        {showShareModal && (
          <div
            onClick={() => setShowShareModal(false)}
            style={{
              position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              zIndex: 100, padding: 20,
            }}
          >
            <div
              onClick={e => e.stopPropagation()}
              style={{
                background: '#fff', borderRadius: 20, padding: '28px 24px',
                width: '100%', maxWidth: 340,
                boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
              }}
            >
              <h3 style={{ fontSize: '1.125rem', color: '#1a202c', marginBottom: 6, textAlign: 'center' }}>
                {lang === 'zh' ? '分享到' : 'Share to'}
              </h3>
              <p style={{ fontSize: '0.8125rem', color: '#a0aec0', marginBottom: 24, textAlign: 'center' }}>
                {lang === 'zh' ? '图片和文案会自动准备好' : 'Image & text will be ready'}
              </p>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                {/* X */}
                <button onClick={() => shareToPlatform('x')} style={{
                  display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8,
                  padding: '16px 12px', borderRadius: 14, border: '1px solid #e2e8f0',
                  background: '#fff', cursor: 'pointer', transition: 'all 0.15s',
                }}>
                  <div style={{ width: 40, height: 40, borderRadius: 10, background: '#000', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="#fff"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" /></svg>
                  </div>
                  <span style={{ fontSize: '0.8125rem', fontWeight: 600, color: '#2d3748' }}>X</span>
                </button>

                {/* 小红书 */}
                <button onClick={() => shareToPlatform('xhs')} style={{
                  display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8,
                  padding: '16px 12px', borderRadius: 14, border: '1px solid #e2e8f0',
                  background: '#fff', cursor: 'pointer', transition: 'all 0.15s',
                }}>
                  <div style={{ width: 40, height: 40, borderRadius: 10, background: '#ff2442', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <span style={{ color: '#fff', fontSize: 16, fontWeight: 800 }}>书</span>
                  </div>
                  <span style={{ fontSize: '0.8125rem', fontWeight: 600, color: '#2d3748' }}>
                    {lang === 'zh' ? '小红书' : 'Xiaohongshu'}
                  </span>
                </button>

                {/* 微信 */}
                <button onClick={() => shareToPlatform('wechat')} style={{
                  display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8,
                  padding: '16px 12px', borderRadius: 14, border: '1px solid #e2e8f0',
                  background: '#fff', cursor: 'pointer', transition: 'all 0.15s',
                }}>
                  <div style={{ width: 40, height: 40, borderRadius: 10, background: '#07c160', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <svg width="22" height="22" viewBox="0 0 24 24" fill="#fff"><path d="M8.691 2.188C3.891 2.188 0 5.476 0 9.534c0 2.22 1.174 4.187 3.014 5.524l-.752 2.268 2.634-1.36a10.2 10.2 0 0 0 3.795.724c.268 0 .532-.013.794-.036a6.014 6.014 0 0 1-.237-1.665c0-3.622 3.36-6.563 7.504-6.563.257 0 .511.014.762.036C16.648 4.974 13.073 2.188 8.691 2.188zm-2.6 4.17a1.12 1.12 0 1 1 0 2.24 1.12 1.12 0 0 1 0-2.24zm5.198 0a1.12 1.12 0 1 1 0 2.24 1.12 1.12 0 0 1 0-2.24zM16.752 9.45c-3.654 0-6.621 2.578-6.621 5.758 0 3.18 2.967 5.757 6.621 5.757a7.9 7.9 0 0 0 2.96-.572l2.058 1.063-.587-1.77c1.438-1.043 2.357-2.58 2.357-4.293-.122-3.297-3.089-5.943-6.788-5.943zm-2.24 3.358a.88.88 0 1 1 0 1.76.88.88 0 0 1 0-1.76zm4.48 0a.88.88 0 1 1 0 1.76.88.88 0 0 1 0-1.76z" /></svg>
                  </div>
                  <span style={{ fontSize: '0.8125rem', fontWeight: 600, color: '#2d3748' }}>
                    {lang === 'zh' ? '微信' : 'WeChat'}
                  </span>
                </button>

                {/* 朋友圈 */}
                <button onClick={() => shareToPlatform('moments')} style={{
                  display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8,
                  padding: '16px 12px', borderRadius: 14, border: '1px solid #e2e8f0',
                  background: '#fff', cursor: 'pointer', transition: 'all 0.15s',
                }}>
                  <div style={{ width: 40, height: 40, borderRadius: 10, background: '#5b7bf9', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="#fff"><circle cx="12" cy="12" r="10" fill="none" stroke="#fff" strokeWidth="1.5" /><circle cx="12" cy="9" r="3" /><path d="M6 18c0-3.314 2.686-5 6-5s6 1.686 6 5" fill="none" stroke="#fff" strokeWidth="1.5" strokeLinecap="round" /></svg>
                  </div>
                  <span style={{ fontSize: '0.8125rem', fontWeight: 600, color: '#2d3748' }}>
                    {lang === 'zh' ? '朋友圈' : 'Moments'}
                  </span>
                </button>
              </div>

              <button
                onClick={() => setShowShareModal(false)}
                style={{
                  width: '100%', marginTop: 20, padding: '12px 0',
                  background: '#f7fafc', border: 'none', borderRadius: 12,
                  fontSize: '0.875rem', color: '#718096', fontWeight: 600, cursor: 'pointer',
                }}
              >
                {lang === 'zh' ? '取消' : 'Cancel'}
              </button>
            </div>
          </div>
        )}

        {/* Share Toast */}
        {shareToast && (
          <div style={{
            position: 'fixed', bottom: 80, left: '50%', transform: 'translateX(-50%)',
            background: '#1a202c', color: '#fff', padding: '12px 24px',
            borderRadius: 12, fontSize: '0.875rem', fontWeight: 500,
            boxShadow: '0 8px 30px rgba(0,0,0,0.2)', zIndex: 200,
            maxWidth: '90vw', textAlign: 'center',
          }}>
            ✅ {shareToast}
          </div>
        )}

        {/* CTAs */}
        <div style={{ textAlign: 'center', paddingTop: 4, display: 'flex', flexDirection: 'column', gap: 12 }}>
          <button className="mbti-btn" onClick={() => { window.location.href = '/'; }} style={{ padding: '14px 32px', background: '#e2e8f0', color: '#4a5568', border: 'none' }}>
            {lang === 'zh' ? '🔄 重新评估' : '🔄 Retake'}
          </button>
        </div>

      </main>
    </div>
  );
}

export default function SubmitPage() {
  return (
    <Suspense fallback={<div style={{ minHeight: '100dvh', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#718096' }}>努力加载人格数据中...</div>}>
      <SubmitContent />
    </Suspense>
  );
}
