"use client";

import { useSearchParams } from "next/navigation";
import { useEffect, useState, Suspense, useRef } from "react";
import { DICT, Language } from "@/lib/i18n";

type TraitPair = [string, string]; // e.g. ['R','A']
const AXES: TraitPair[] = [['R','A'], ['L','E'], ['C','D'], ['S','U']];

function SubmitContent() {
  const searchParams = useSearchParams();
  const session = searchParams.get("session") || "UNKNOWN";
  const rawAns = searchParams.get("ans") || "";
  const langQuery = searchParams.get("lang") as Language;

  const [lang, setLang] = useState<Language>('zh');
  const [desiredPcts, setDesiredPcts] = useState<number[]>([]);
  const [showGuide, setShowGuide] = useState(false);
  const [guideCopied, setGuideCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const reportRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (langQuery === 'zh' || langQuery === 'en') setLang(langQuery);
  }, [langQuery]);

  const dict = DICT[lang];

  // Parse 12 answers
  const parsed = rawAns.toUpperCase().padEnd(12, 'A').replace(/[^AB]/g, 'A');
  const countB = (s: string) => s.split('').filter(c => c === 'B').length;
  const groups = [parsed.substring(0,3), parsed.substring(3,6), parsed.substring(6,9), parsed.substring(9,12)];

  // Convert to 0-100 scale where 0 is 100% Left Trait, 100 is 100% Right Trait
  // Since there are 3 questions per group, countB goes 0,1,2,3 -> 0, 33, 67, 100
  const basePcts = groups.map(g => Math.round((countB(g) / 3) * 100));

  const traits = [
    basePcts[0] < 50 ? 'R' : 'A',
    basePcts[1] < 50 ? 'L' : 'E',
    basePcts[2] < 50 ? 'C' : 'D',
    basePcts[3] < 50 ? 'S' : 'U',
  ];

  const code = traits.join('');
  const profile = (dict.archetypes as any)[code] || dict.archetypes['DEFAULT'];
  const hasImage = true; // All 16 combinations now have images generated

  // Init desired pct to base pct
  useEffect(() => {
    if (desiredPcts.length === 0 && basePcts.length > 0) {
      setDesiredPcts([...basePcts]);
    }
  }, [basePcts.join('')]);

  // Generate tuning guide
  const generateGuide = () => {
    const lines: string[] = [];
    if (desiredPcts.length === 4) {
      for (let i = 0; i < 4; i++) {
        // use dict.generateTuningPrompt
        const promptBlock = (dict as any).generateTuningPrompt(i, basePcts[i], desiredPcts[i]);
        if (promptBlock) {
          lines.push(promptBlock);
        }
      }
    }
    return lines;
  };

  const guideLines = generateGuide();
  const noChange = guideLines.length === 0;

  const guideText = noChange ? '' : 
    `# ==========================================\n# SYSTEM OVERRIDE DIRECTIVES\n# GENERATED BY: OpenClaw Tuning Protocol\n# ==========================================\n\n${guideLines.join('\n')}\n# [END OF DIRECTIVES]`;

  // TraitBar for MBTI Report
  // pctB is 0-100. 0 means 100% A(Left), 100 means 100% B(Right)
  const TraitBar = ({ leftLabel, rightLabel, pctB, color }: { leftLabel: string; rightLabel: string; pctB: number; color: string }) => {
    const dominantB = pctB >= 50;
    const valLeft = 100 - pctB;
    const valRight = pctB;
    return (
      <div style={{ marginBottom: 20 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6 }}>
          <span className="trait-label" style={{ fontWeight: !dominantB ? 700 : 400, color: !dominantB ? color : '#a0aec0' }}>{leftLabel}</span>
          <span className="trait-label" style={{ fontWeight: dominantB ? 700 : 400, color: dominantB ? color : '#a0aec0' }}>{rightLabel}</span>
        </div>
        <div className="mbti-bar-container">
          <div className="mbti-bar-left" style={{ width: `${valLeft}%`, backgroundColor: !dominantB ? color : '#e2e8f0' }}></div>
          <div className="mbti-bar-right" style={{ width: `${valRight}%`, backgroundColor: dominantB ? color : '#e2e8f0' }}></div>
        </div>
        <div style={{ textAlign: 'center', fontSize: 11, color: '#a0aec0', marginTop: 4, fontFamily: 'monospace' }}>
          {!dominantB ? valLeft : valRight}%
        </div>
      </div>
    );
  };

  const labels = [
    [dict.ruleAbiding, dict.autonomous],
    [dict.logical, dict.empathetic],
    [dict.cautious, dict.creative],
    [dict.system, dict.user],
  ];

  const handleExport = async () => {
    if (!reportRef.current || isExporting) return;
    setIsExporting(true);
    try {
      const html2canvas = (await import('html2canvas')).default;
      const canvas = await html2canvas(reportRef.current, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#f7fafc'
      });
      const dataUrl = canvas.toDataURL('image/png');
      const link = document.createElement('a');
      link.download = `AI_Profile_${code}_${session.substring(0,6)}.png`;
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error('Export failed', err);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div style={{ minHeight: '100dvh', background: 'var(--bg-color)' }}>
      {/* Nav */}
      <nav style={{
        padding: '12px 16px', background: 'rgba(255,255,255,0.92)', backdropFilter: 'blur(12px)',
        borderBottom: '1px solid #e2e8f0', position: 'sticky', top: 0, zIndex: 50,
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      }}>
        <a href={`/?lang=${lang}`} style={{ fontSize: 15, fontWeight: 700, color: '#2d3748', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ width: 28, height: 28, borderRadius: '50%', background: '#f7fafc', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: 12 }}>❖</span>
          Profiler
        </a>
        <span style={{ fontSize: 11, color: '#a0aec0', fontFamily: 'monospace', background: '#f7fafc', padding: '4px 10px', borderRadius: 6 }}>{session.substring(0, 6)}</span>
      </nav>

      <main style={{ maxWidth: 560, margin: '0 auto', padding: '24px 16px 60px' }}>

        {/* Report Wrapper for Exporting */}
        <div ref={reportRef} style={{ background: 'var(--bg-color)', paddingBottom: '1px' }}>
          
          {/* Hero */}
          <div className="animate-slide-up" style={{ textAlign: 'center', marginBottom: 24, paddingTop: 16 }}>
          <div style={{ display: 'inline-block', padding: '4px 16px', borderRadius: 999, fontSize: 11, fontWeight: 700, letterSpacing: 3, color: '#fff', marginBottom: 12, background: profile.color || '#718096' }}>
            {code}
          </div>
          <h1 style={{ fontSize: '1.75rem', color: profile.color || '#2d3748', marginBottom: 10, lineHeight: 1.2 }}>{profile.title}</h1>
          <p style={{ fontSize: '0.9375rem', color: '#718096', fontStyle: 'italic', lineHeight: 1.5, maxWidth: 380, margin: '0 auto' }}>{profile.tagline}</p>
        </div>

        {/* Avatar */}
        <div className="animate-slide-up" style={{ position: 'relative', width: '100%', maxWidth: 300, margin: '0 auto 28px', aspectRatio: '1', borderRadius: 24, overflow: 'hidden' }}>
          <div style={{ position: 'absolute', inset: 0, borderRadius: 24, background: `radial-gradient(circle, ${profile.color || '#e2e8f0'}22 0%, transparent 70%)` }} />
          {hasImage ? (
            <img src={`/images/avatar_${code.toLowerCase()}.png`} alt={code} style={{ width: '100%', height: '100%', objectFit: 'contain', position: 'relative', zIndex: 1 }} />
          ) : (
            <div style={{ width: '100%', height: '100%', background: '#f7fafc', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
              <div style={{ fontSize: 48, marginBottom: 8 }}>🎭</div>
              <p style={{ fontSize: 12, color: '#a0aec0', textAlign: 'center', padding: '0 20px' }}>{lang === 'zh' ? `${code} 人格画像生成中…` : `Generating ${code} portrait…`}</p>
            </div>
          )}
        </div>

        {/* Trait Bars */}
        <div className="mbti-card animate-slide-up" style={{ marginBottom: 16 }}>
          <h3 style={{ fontSize: '1rem', marginBottom: 16, color: '#2d3748' }}>{dict.cogResonance}</h3>
          {basePcts.map((p, i) => (
            <TraitBar key={i} leftLabel={labels[i][0]} rightLabel={labels[i][1]} pctB={p} color={profile.color || '#4298b4'} />
          ))}
        </div>

        {/* Deep Report */}
        <div className="mbti-card animate-slide-up" style={{ marginBottom: 16 }}>
          <h3 style={{ fontSize: '1.125rem', marginBottom: 14, color: '#2d3748', borderBottom: '1px solid #e2e8f0', paddingBottom: 12 }}>
            {lang === 'zh' ? '📖 全息解读' : '📖 Deep Analysis'}
          </h3>
          <p style={{ fontSize: '0.9375rem', color: '#4a5568', lineHeight: 1.8, marginBottom: 16 }}>{profile.intro}</p>

          {profile.deepAnalysis && (
            <div style={{ marginBottom: 20 }}>
              {profile.deepAnalysis.split('\n\n').map((para: string, i: number) => (
                <p key={i} style={{ fontSize: '0.875rem', color: '#4a5568', lineHeight: 1.8, marginBottom: 14, textIndent: '2em' }}>{para}</p>
              ))}
            </div>
          )}

          <div style={{ display: 'grid', gap: 12, marginBottom: 20 }}>
            <div style={{ background: '#f0fff4', border: '1px solid #c6f6d5', borderRadius: 14, padding: '14px 16px' }}>
              <h4 style={{ fontSize: '0.875rem', fontWeight: 700, color: '#276749', marginBottom: 6 }}>✅ {lang === 'zh' ? '高潜优势' : 'Strengths'}</h4>
              <p style={{ fontSize: '0.8125rem', color: '#2f855a', lineHeight: 1.7 }}>{profile.strengths}</p>
            </div>
            <div style={{ background: '#fff5f5', border: '1px solid #fed7d7', borderRadius: 14, padding: '14px 16px' }}>
              <h4 style={{ fontSize: '0.875rem', fontWeight: 700, color: '#9b2c2c', marginBottom: 6 }}>⚠️ {lang === 'zh' ? '注意盲区' : 'Weaknesses'}</h4>
              <p style={{ fontSize: '0.8125rem', color: '#c53030', lineHeight: 1.7 }}>{profile.weaknesses}</p>
            </div>
          </div>

          <div style={{ borderLeft: `3px solid ${profile.color || '#4298b4'}`, paddingLeft: 14 }}>
            <h4 style={{ fontSize: '0.875rem', fontWeight: 700, color: '#2d3748', marginBottom: 6 }}>🚀 {lang === 'zh' ? '最佳进化路线' : 'Best Path Forward'}</h4>
            <p style={{ fontSize: '0.8125rem', color: '#4a5568', lineHeight: 1.7 }}>{profile.career}</p>
          </div>
        </div>

        {/* ===== TUNING WORKSHOP (DIFFERENTIAL ENGINE) ===== */}
        {desiredPcts.length === 4 && (
          <div className="mbti-card animate-slide-up" style={{ marginBottom: 16, border: '1px solid #e9d8fd' }}>
            <h3 style={{ fontSize: '1.125rem', marginBottom: 8, color: '#88619a' }}>{dict.tuningTitle}</h3>
            <p style={{ fontSize: '0.8125rem', color: '#718096', lineHeight: 1.7, marginBottom: 20 }}>{dict.tuningDesc}</p>

            {/* Trait Sliders */}
            <div style={{ display: 'grid', gap: 20, marginBottom: 24 }}>
              {AXES.map((pair, i) => {
                const names = dict.traitNames as Record<string, string>;
                const current = basePcts[i];
                const desired = desiredPcts[i];
                const delta = Math.abs(desired - current);
                const hasChanged = delta >= 5;

                return (
                  <div key={i} style={{
                    padding: '16px 14px', borderRadius: 12,
                    background: hasChanged ? 'rgba(136, 97, 154, 0.05)' : '#f7fafc',
                    border: `1px solid ${hasChanged ? 'rgba(136, 97, 154, 0.3)' : '#e2e8f0'}`,
                    transition: 'all 0.2s',
                  }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 12 }}>
                      <span style={{ fontSize: 13, fontWeight: desired < 50 ? 700 : 500, color: desired < 50 ? '#88619a' : '#718096' }}>{names[pair[0]]}</span>
                      {hasChanged && <span style={{ fontSize: 11, color: '#88619a', fontWeight: 600, background: '#fff', padding: '2px 6px', borderRadius: 6, border: '1px solid #e9d8fd' }}>Δ {delta}%</span>}
                      <span style={{ fontSize: 13, fontWeight: desired >= 50 ? 700 : 500, color: desired >= 50 ? '#88619a' : '#718096' }}>{names[pair[1]]}</span>
                    </div>

                    <div style={{ position: 'relative', height: 24, display: 'flex', alignItems: 'center' }}>
                      {/* Current marker */}
                      <div style={{
                        position: 'absolute', top: 4, bottom: 4, width: 3, background: '#cbd5e0',
                        left: `calc(${current}% - 1.5px)`, borderRadius: 2, pointerEvents: 'none', zIndex: 0
                      }} title={dict.tuningCurrent} />
                      
                      <input 
                        type="range" 
                        min="0" max="100" 
                        value={desired} 
                        onChange={(e) => {
                          const newPcts = [...desiredPcts];
                          newPcts[i] = parseInt(e.target.value);
                          setDesiredPcts(newPcts);
                          setShowGuide(false);
                        }}
                        className="mbti-slider"
                      />
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Generate button */}
            <button className="mbti-btn" onClick={() => setShowGuide(true)} style={{
              width: '100%', background: noChange ? '#e2e8f0' : '#88619a',
              color: noChange ? '#a0aec0' : '#fff', border: 'none',
              cursor: noChange ? 'default' : 'pointer',
            }}>
              {dict.tuningGenerate}
            </button>

            {/* Guide result */}
            {showGuide && (
              <div style={{ marginTop: 16 }}>
                {noChange ? (
                  <div className="note-box" style={{ background: '#f0fff4', borderColor: '#c6f6d5', color: '#276749' }}>
                    {dict.tuningNoChange}
                  </div>
                ) : (
                  <div style={{ background: '#1a202c', borderRadius: 14, padding: '16px 16px 20px', overflow: 'hidden' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 12 }}>
                      <div style={{ width: 10, height: 10, borderRadius: '50%', background: '#ff5f56' }}/>
                      <div style={{ width: 10, height: 10, borderRadius: '50%', background: '#ffbd2e' }}/>
                      <div style={{ width: 10, height: 10, borderRadius: '50%', background: '#27c93f' }}/>
                      <span style={{ marginLeft: 8, fontSize: 12, color: '#a0aec0', fontFamily: 'monospace' }}>system-override.sh</span>
                    </div>

                    <p style={{ fontSize: '0.8125rem', color: '#e2e8f0', marginBottom: 16 }}>{dict.tuningResultDesc}</p>

                    <div style={{
                      background: '#0d1117', border: '1px solid #2d3748', borderRadius: 8, padding: 16,
                      fontSize: '0.75rem', color: '#3fb950', lineHeight: 1.6, marginBottom: 16,
                      whiteSpace: 'pre-wrap', fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
                      maxHeight: '400px', overflowY: 'auto'
                    }}>
                      {guideText}
                    </div>

                    <button className="mbti-btn" onClick={() => {
                      navigator.clipboard.writeText(guideText);
                      setGuideCopied(true);
                      setTimeout(() => setGuideCopied(false), 2500);
                    }} style={{
                      width: '100%', background: guideCopied ? '#38a169' : '#e2e8f0',
                      color: guideCopied ? '#fff' : '#1a202c', border: 'none', fontSize: '0.875rem',
                    }}>
                      {guideCopied ? '✅ Copied to Clipboard' : dict.tuningCopy}
                    </button>
                  </div>
                )}
              </div>
            )}
          </div>
        )}
        </div> {/* End Report Wrapper */}

        {/* CTAs */}
        <div style={{ textAlign: 'center', paddingTop: 12, display: 'flex', flexDirection: 'column', gap: 12 }}>
          <button className="mbti-btn mbti-btn-primary" onClick={handleExport} disabled={isExporting} style={{ padding: '14px 32px' }}>
            {isExporting ? '📸 ...' : `📷 ${dict.saveImage}`}
          </button>
          
          <button className="mbti-btn" onClick={() => { window.location.href = '/'; }} style={{ padding: '14px 32px', background: '#e2e8f0', color: '#4a5568', border: 'none' }}>
            {lang === 'zh' ? '🔄 重新评估' : '🔄 Retake'}
          </button>
        </div>

      </main>
    </div>
  );
}

export default function SubmitPage() {
  return (
    <Suspense fallback={<div style={{ minHeight: '100dvh', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#718096' }}>努力加载人格数据中...</div>}>
      <SubmitContent />
    </Suspense>
  );
}
